### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by jaiisabarish** [sherwyn11/Medi-Care#2]
Can u plz provide the step wise details to run this project

**Comment by sherwyn11** [comment]
1. Deploy Smart Contracts on Private Ethereum Blockchain Network using the tools from Truffle Suite
```bash
cd blockchain
truffle migrate --reset
``` 
2. Run React development server
```bash
cd blockchain
npm start
```
3. Run Flask server
```bash
cd server
python app.py
