### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by jaiisabarish** [sherwyn11/Medi-Care#4]
It's getting a file storing it in ipfs and returns a hash
Giving the hash to the analyze endpoint retrieves the file from ipfs and parses the image but not storing the hash in the blockchain ..it is not using smart contracts !!

**Comment by sherwyn11** [comment]
It is storing the hash in the Blockchain through smart contracts. Check the Upload.js file in the components directory.

```javascript
this.state.patient.methods.saveFile(this.state.fname, this.state.fhash, today).send({ from: this.state.account })
        .once('receipt', (receipt) => {
            console.log(receipt);
          this.setState({ loading: false })
        })
```
