### ISSUE TITLE
Python app.py ConnectionRefusedError

### ISSUE THREAD

**Issue by ThotapalliAswin** [sherwyn11/Medi-Care#8]
Hi, I am sorry if this a basic question, I am just starting out and I am having issues when I try to execute your application.
The process I did is 

`cd blockchain`
`ganache-cli`

`cd blockchain`
`truffle migrate --reset`

`cd blockchain`
`npm start`

`cd server`
`python3 app.py`

I am getting this error on running python3 app.py
![Screenshot (5)](https://user-images.githubusercontent.com/38395105/176949645-3b842c90-5143-4870-9e2f-3084a86f7329.png)

What am I doing wrong? Can anyone help me out please.

**Comment by sherwyn11** [comment]
Is your IPFS daemon running?

**Comment by ThotapalliAswin** [comment]
> Is your IPFS daemon running?

No it's not. At what stage do I start IPFS. Before or after ganache-cli?

Thank you for the quick reply

**Comment by sherwyn11** [comment]
Start it before you start the server. Sorry I didn’t mention it in the documentation!

**Comment by ThotapalliAswin** [comment]
> Start it before you start the server. Sorry I didn’t mention it in the documentation!

Thanks. I finally got it running but when I open http://127.0.0.1:5000, all I get is "TEST WORKS". How do I access the actual application?
I am really sorry for these basic questions, I am new to all these and I am still figuring things out.

**Comment by sherwyn11** [comment]
You are hitting the backend url hence you see "TEST WORKS". Run the react development server as mentioned in the documentation.

**Comment by ThotapalliAswin** [comment]
> You are hitting the backend url hence you see "TEST WORKS". Run the react development server as mentioned in the documentation.

I am already running 
'npm start'  for the react server.
What am I missing?

**Comment by ThotapalliAswin** [comment]
I am getting this error when I try to run `npm install`

![Screenshot (6)](https://user-images.githubusercontent.com/38395105/176986301-7770eab6-2b35-43ec-8c7c-aaad39b56e75.png)
![Screenshot (7)](https://user-images.githubusercontent.com/38395105/176986310-6e7194f8-755c-42fc-be56-e4daa35ed786.png)

**Comment by sherwyn11** [comment]
It is working when I try npm install. Please check if you're in the right directory.

**Comment by ThotapalliAswin** [comment]
It is working fine now, thanks. The issue was my version of Ubuntu was not installing node and npm properly
